platform :ios, '14.0'

target 'SportScanner' do

  use_frameworks!

    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'LookinServer', '~> 1.0.2', :configurations => ['Debug']
    #Swift库
    pod 'SnapKit', '~> 5.0.0'
    pod 'Hero'
    pod 'lottie-ios'
    pod 'Moya/Combine', '~> 15.0'
    pod 'SwiftyJSON'
    pod 'SwiftDate'
    pod 'CBFlashyTabBarController'
    pod 'Kingfisher'
    pod 'URLNavigator'
    pod 'ESPullToRefresh'
    pod 'SkeletonView'
end
